site_name: Deep Blue Robotics
theme: 
  name: material
  logo: images/logo.png
  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      linenums: true

nav:
  - Home: index.md
  - Getting Started: start.md
  - 1. Syntax, Variables, and Types: 
    - Hello World: week-1/hello-world.md
    - Variables: week-1/variables.md
    - Types: week-1/types.md
    - Additional Exercises: week-1/exercises.md