site_name: Deep Blue Robotics
theme: 
  name: material
  logo: images/logo.png

extra:
  social:
    - type: github
      link: https://github.com/kevinzwang/training

repo_name: 'DeepBlueRobotics/training'
repo_url: 'https://github.com/DeepBlueRobotics/training'

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - mdx_math
  - toc:
      permalink: true

nav:
  - Home: index.md
  - 0. Java Basics: section-0/index.md
  - 1. Electronics and Pneumatics:
    - Introduction: section-1/intro.md
    - Electronics: section-1/electronics.md
    - Pneumatics: section-1/pneumatics.md
  - 2. Robot Code and Version Control:
    - Introduction: section-2/intro.md
    - Setup: section-2/setup.md
    - Code Structure: section-2/code-structure.md
    - Version Control: section-2/version-control.md
  - 3. Developing Robot Code:
    - Introduction: section-3/intro.md
    - JavaDocs and WPILib: section-3/wpilib.md
    - Commands and Subsystems: section-3/commands-subsystems.md
    - Advanced Version Control: section-3/version-control2.md
  - 4. Drivetrain Project:
    - Introduction: section-4/intro.md
    - Teleoperated Period: section-4/teleop.md
    - Autonomous Period: section-4/auton.md
  - 5. Unit Testing:
    - Introduction: section-5/intro.md
    - Why Unit Tests?: section-5/why-tests.md
    - Writing Tests: section-5/writing-tests.md
    - Continuous Integration: section-5/ci.md
  - 6. Build Season Process:
    - Introduction: section-6/intro.md
    - Branch Organization: section-6/organization.md
    - Task Delegation: section-6/delegation.md
    - PRs and Code Reviews: section-6/pull-requests.md
  - 7. Advanced Programming:
    - Introduction: section-7/intro.md
    - Common Sensors: section-7/sensors.md
    - PID Control: section-7/pid-control.md
    - Odometry and Kinematics: section-7/odometry-kinematics.md
    - Drivetrain Characterization: section-7/drivetrain-characterization.md
    - Autonomous Pathing: section-7/pathweaver.md
    - Limelight: section-7/limelight.md
    - Swerve Drivetrains: section-7/swerve-drive.md
  - Contributing: 
    - Introduction: contributing/intro.md
    - With Python: contributing/with-python.md
    - With Docker: contributing/with-docker.md
    - Yearly Checklist: contributing/yearly-checklist.md
    - Resources: contributing/resources.md
  - Resources: resources.md
