site_name: Deep Blue Robotics
theme: 
  name: material
  logo: images/logo.png

extra:
  social:
    - type: github
      link: https://github.com/kevinzwang/training

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      linenums: true

nav:
  - Home: index.md
  - Getting Started: start.md
  - 1. Syntax, Variables, and Types: 
    - Introduction: week-1/intro.md
    - Hello World: week-1/hello-world.md
    - Variables: week-1/variables.md
    - Types: week-1/types.md
    - Additional Exercises: week-1/exercises.md
  - 5. OOP and Robot Code:
    - Introduction: week-5/intro.md
    - Classes and Objects: week-5/classes-objects.md
    - Packages and Access: week-5/packages-access.md
    - Robot Code: week-5/robot-code.md
    - Additional Exercises: week-5/exercises.md
  - Other:
    - Contributing: other/contributing.md

