site_name: Deep Blue Robotics
theme: 
  name: material
  logo: images/logo.png

extra:
  social:
    - type: github
      link: https://github.com/kevinzwang/training

repo_name: 'DeepBlueRobotics/training'
repo_url: 'https://github.com/DeepBlueRobotics/training'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      linenums: true
  - toc:
      permalink: true

nav:
  - Home: index.md
  - 0. Java Basics: section-0/index.md
  - 1. Electronics and Pneumatics:
    - Introduction: section-1/intro.md
    - Electronics: section-1/electronics.md
    - Pneumatics: section-1/pneumatics.md
  - 2. Robot Code and Version Control:
    - Introduction: section-2/intro.md
    - Setup: section-2/setup.md
    - Robot Code: section-2/robot-code.md
    - Version Control: section-2/version-control.md
    - Additional Exercises: section-2/exercises.md
  - 4. Drivetrain code:
    - Introduction: section-4/intro.md
    - Let's do it!: section-4/doing-it.md
  - Other:
    - Contributing: other/contributing.md

