name: Java CI

on: [push]

jobs:
  build-training:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: cd code/TrainingRobot && ./gradlew build
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      # We only run tests if the code changed because we expect them to fail
      # except when a student is actually changing code/tests.
      run: cd code/TestRobot && ./gradlew `if git diff --quiet master -- .; then echo build; else echo assemble; fi